version: "3.7"
services:
  db:
    image: "postgres:11-alpine"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgres"
      POSTGRES_DB: "db"
    volumes:
    - "./db/server.crt:/var/lib/postgresql/server.crt:ro"
    - "./dbserver.key:/var/lib/postgresql/server.key:ro"
    command:
    - "-c"
    - "ssl_cert_file=/var/lib/postgresql/server.crt"
    - "-c"
    - "ssl_key_file=/var/lib/postgresql/server.key"

  pgbouncer:
    build:
      context: "pgbouncer"
      dockerfile: "Dockerfile"
    depends_on:
    - "db"
    command:
    - "pgbouncer"
    - "/etc/pgbouncer/pgbouncer.ini"
    ports:
    - "15432:5432"
    volumes:
    - "./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro"
    - "./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro"

  migrations:
    build:
      context: "migrations"
      dockerfile: "Dockerfile"
    environment:
      DATABASE_URL: "postgres://postgres:p0stgres@db/db"
    depends_on:
    - "db"
    command:
    - "goose"
    - "-env"
    - "development"
    - "up"
    volumes:
    - "./migrations/db:/go/db:ro"
