version: "3.7"
services:
  db:
    image: "postgres:11-alpine"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgres"
      POSTGRES_DB: "db"
    ports:
    - "25432:5432"

  pgbouncer:
    build:
      context: "pgbouncer"
      dockerfile: "Dockerfile"
    depends_on:
    - "db"
    command:
    - "pgbouncer"
    - "/etc/pgbouncer/pgbouncer.ini"
    ports:
    - "15432:5432"
    volumes:
    - "./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro"
    - "./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro"

  migrations:
    image: "amacneil/dbmate"
    environment:
      DATABASE_URL: "postgres://postgres:p0stgres@db/db?sslmode=disable"
    depends_on:
    - "db"
    - "pgbouncer"
    command:
    - "up"
    volumes:
    - "./migrations/db:/db:ro"
